function [T, positions, R_stack] = forwardKinematics_franka(q)
% FORWARDKINEMATICS_FRANKA  Approximate forward kinematics for Franka Panda arm.
%   [T, positions, R_stack] = forwardKinematics_franka(q)
%
% Input:
%   q : 7x1 joint angles (rad)
%
% Outputs:
%   T         : 4x4 homogeneous transform of end-effector (tool frame)
%   positions : 8x3 points of joint origins (base = row1, after each joint)
%   R_stack   : 3x3x8 rotation matrices (optional use)
%
% Reference (approx DH, simplified):
%   Using modified DH parameters (not full accuracy of official model) for reproducibility:
%   i | alpha_{i-1} | a_{i-1} | d_i     | theta_i (variable)
%   1 |    0        |   0     | 0.333   | q1
%   2 |   -pi/2     |   0     |   0     | q2
%   3 |    pi/2     |   0     | 0.316   | q3
%   4 |    pi/2     | 0.0825  |   0     | q4
%   5 |   -pi/2     | -0.0825 | 0.384   | q5
%   6 |    pi/2     |   0     |   0     | q6
%   7 |    pi/2     | 0.088   | 0.107   | q7
% (Tool extension ~0.1m optional not included here)
%
% NOTE: This is an approximate model aimed at algorithm development / RL abstraction.
%       For precise manipulation or collision checking, replace with verified parameters.
%
% Validation: Use verify_fk_with_urdf (if Robotics System Toolbox + URDF available).
%
% Author: autogenerated template

q = q(:);
if numel(q)~=7; error('Expected 7 joint angles.'); end

alpha = [0, -pi/2,  pi/2,  pi/2, -pi/2,  pi/2,  pi/2];
a     = [0,     0,     0, 0.0825, -0.0825, 0, 0.088];
d     = [0.333, 0, 0.316, 0, 0.384, 0, 0.107];

T = eye(4);
positions = zeros(8,3);
R_stack = zeros(3,3,8);
positions(1,:) = [0 0 0];
R_stack(:,:,1) = eye(3);

for i=1:7
    A = dhTransform(alpha(i), a(i), d(i), q(i));
    T = T * A;
    positions(i+1,:) = T(1:3,4)';
    R_stack(:,:,i+1) = T(1:3,1:3);
end

end

function A = dhTransform(alpha, a, d, theta)
    ca = cos(alpha); sa = sin(alpha);
    ct = cos(theta); st = sin(theta);
    A = [ ct, -st, 0, a;
          st*ca, ct*ca, -sa, -d*sa;
          st*sa, ct*sa,  ca,  d*ca;
          0, 0, 0, 1];
end
